import React from 'react';
import PropTypes from 'prop-types';

const setHighContrastMode = (onOrOff) => {
  console.log('will set high contrast mode to', onOrOff);
};

// TODO break this up. For now it's just a replica of what
// was being generated by ERB
const ShowPageWrapper = (props) => {
  const isHighContrastMode = true;
  const loaded = true;

  return (
    <div>
      <a href="#skiptocontent" tabIndex="1" className="skip">Skip to content</a>

      <div className="dashboard__top-bar">
        <section>
          <div className="phase-banner">
            <div className="container">
              <div className="row">
                <div className="col-xs-12">
                  <span>This is a beta. Help us make it better for you - please <a href="/feedback" className="UIK-link">give feedback</a>.</span>
                </div>
              </div>
            </div>
          </div>
        </section>

        <header className="main__header" role="banner">
          <div className="govau-header ">
            <div className="container">
              <div className="govau-header__container">
                <div className="govau-header__container__logo">
                  <a href="/">
                    <img
                      src="/images/performance-dashboard-logo.svg?87b2f2845055654510e3c36ef2cf8a9e"
                      width="394"
                      height="29"
                      alt="Performance Dashboards"
                    />
                  </a>
                </div>

                <div className="govau-header__container__utils">
                  <div className="toggle-switch">
                    <label className="switch-light switch-material">
                      <strong className="switch-text">High contrast mode</strong>
                      <input
                        type="checkbox"
                        id="high-contrast-switch"
                        onChange={(e) => setHighContrastMode(e.target.value)}
                      />
                      {/*The below empty elements are needed for the toggle switch CSS*/}
                      <span>
                        <span />
                        <span />
                        <a />
                      </span>
                    </label>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </header>
      </div>

      <main role="main" id="skiptocontent">
        <div>
          <div id="dashboard-show-app">
            {loaded && props.children}

            {!loaded && (
              <div className="hero-region">
                <div className="container">
                  <div className="row">
                    <div className="col-xs-12">
                      <div className="D-loading-panel">
                        <span>Loading...</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          <div className="below-the-line-bg">
            <div className="container">
              <div className="row">
                <div className="col-xs-12">
                  <div className="D_widget-card widget dashboard-information">
                    <div className="row">
                      <div className="col-xs-12 col-lg-7">
                        <div className=" widget-text">
                          <div className="widget-text__inner">
                            <div className="widget__title">
                              <h4>Dashboard Information</h4>
                            </div>

                            <div id="dashboard-notes" className="widget__body">
                              <dl>
                                <dt>Where is this information from?</dt>
                                <dd>Department of Immigration and Border Protection.</dd>
                                <dt>What is Australian Citizenship Appointment Booking Service?</dt>
                                <dd>The Australian Citizenship Appointment Booking Service makes it quicker, easier and more convenient for users to reschedule a citizenship test appointment. Prior to the introduction of the online service, users were only able to change their appointment by calling the Department. The public beta release of the service is currently available in Melbourne, Victoria.</dd>
                                <dt>User satisfaction</dt>
                                <dd>User satisfaction measures the percentage of users who responded "satisfied" and "very satisfied" with the appointment booking service using the feedback kiosks located in the Department’s citizenship areas.</dd>
                                <dt>Cost per transaction</dt>
                                <dd>This data is not available.</dd>
                                <dt>Digital take-up</dt>
                                <dd>Digital take-up measures the number of users who had an appointment booked using the new service as a percentage of all appointments that have been made Australia-wide.</dd>
                                <dt>Completion rate</dt>
                                <dd>Completion rate measures the number of users who were able to use the digital service without having to contact the Department for assistance when rescheduling their appointment.</dd>
                              </dl>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div className="col-xs-12 col-lg-5">
                        <div className="widget-text__footer">
                          <ul>
                            <li>
                              <a href="https://www.border.gov.au/" target="_blank" className="link--external-alt"> Visit https://www.border.gov.au/</a>
                            </li>

                            <li>
                              <a className="link--external-alt" href="/dashboards/2-australian-citizenship-appointment-booking-service/export.csv">
                                Download dashboard data as CSV
                              </a>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer role="contentinfo">
        <div className="govau-footer">
          <div className="container">
            <div className="govau-footer__container">
              <div className="govau-footer__container__logo">
                <img
                  src="/images/coat-of-arms.png?c4be90534c4a1531dc37d580dcbb6074"
                   width="185"
                   height="135"
                   alt="Commonwealth of Australia Coat of Arms Logo"
                />
              </div>

              <div className="govau-footer__container__utils">
                <div className="line-1">
                  <ul className="list-unstyled govau-footer__links-list">
                    <li><a href="/editor" className="UIK-link">Editor sign in</a></li>
                    <li><a href="https://www.dto.gov.au/standard/" rel="external" className="UIK-link" target="_blank">Digital Service Standard</a></li>
                    <li><a href="https://www.dto.gov.au/standard/11-measure-performance/" rel="external" className="UIK-link" target="_blank">About Performance Measurement</a></li>
                    <li><a href="/api" className="UIK-link">Dashboard API</a></li>
                    <li><a href="/copyright" className="UIK-link">Copyright</a></li>
                    <li><a href="https://www.dto.gov.au/blog/" rel="external" className="UIK-link" target="_blank">DTA Blog</a></li>
                    <li><a href="/feedback" className="UIK-link">Please give feedback</a></li>
                  </ul>
                </div>

                <div className="line-2">
                  <small>© Commonwealth of Australia</small>
                  <p className="small">This work is licensed under a Creative Commons Attribution 3.0 International <a href="https://creativecommons.org/licenses/by/3.0/au/deed.en" className="UIK-link " rel="external">License</a></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

ShowPageWrapper.propTypes = {
  children: PropTypes.oneOfType([
    PropTypes.array,
    PropTypes.element,
  ]),
};

export default ShowPageWrapper;
